baseURL = "https://examplesite.com/"
title = "ExampleSite"
paginate = 5
theme = "hugo-theme-stack-3.21.0"


[[menu.main]]
  identifier = "categories"
  name = "posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "example"
  name = "example.org"
  url = "https://example.org"
  weight = 30

[markup.highlight]
  noClasses = false
